Repository TIL-Log-lab/Tilog-server-node-v2, pull requests merged in 2022-04, with the labels that each got.

#5 개발용 Docker compose 환경 구성
  .gitignore
  docker/docker-compose.yml
  docker/mysql/mysql-init-files/init.sql
Labels: enhancement

#9 필수 패키지, Path alias 설정
  library/utils/date/date.ts
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/main.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#10 필수 패키지 설치 및 구성
  library/all-exceptions/all-exception.filter.ts
  library/all-exceptions/index.ts
  library/all-exceptions/interface/exception-message.interface.ts
  library/open-api/index.ts
  library/open-api/swagger-document-builder.ts
  library/utils/constants/constants.ts
  library/utils/index.ts
  package.json
  src/app.module.ts
  src/main.ts
  tsconfig.json
  yarn.lock
Labels: documentation, enhancement

#6 Prisma연동, 스키마 마이그레이션 작업
  environments/readme.md
  package.json
  prisma/migrations/20220410153137_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  yarn.lock
Labels: documentation, enhancement, help wanted

#12 Prisma 서비스 작성, 환경변수 관리 서비스 구성, 가이드라인 예제 코드 작성
  .eslintrc.js
  environments/validationSchema.ts
  library/all-exceptions/all-exception.filter.ts
  library/prisma/index.ts
  library/prisma/prisma.module.ts
  library/prisma/prisma.service.ts
  nest-cli.json
  package.json
  src/app.module.ts
  src/example/code/dto/get-code.dto.ts
  src/example/code/example-code.controller.ts
  src/example/code/example-code.decorator.ts
  src/example/code/example-code.repository.ts
  src/example/code/example-code.service.ts
  src/example/example.module.ts
  src/main.ts
  tsconfig.json
  yarn.lock
Labels: documentation, enhancement

#18 인증에 필요한 패키지 추가, 데이터베이스 마이그레이션
  docker/docker-compose.yml
  environments/validationSchema.ts
  library/all-exceptions/interface/exception-message.interface.ts
  package.json
  prisma/migrations/20220411145117_delete_users_column/migration.sql
  prisma/migrations/20220412152427_create_users_auth_table/migration.sql
  prisma/migrations/20220412154059_add_users_columns/migration.sql
  prisma/migrations/20220413050210_copy_users_provider_server_id/migration.sql
  prisma/schema.prisma
  yarn.lock
Labels: bug, enhancement

#19 회원가입, 로그인 토큰발급, 로그아웃
  environments/readme.md
  environments/validationSchema.ts
  library/all-exceptions/all-exception.filter.ts
  library/all-exceptions/interface/exception-message.interface.ts
  library/utils/cookie/cookie.service.ts
  library/utils/guards/auth/github-auth.guard.ts
  library/utils/guards/auth/strategy/github.strategy.ts
  package.json
  prisma/migrations/20220412152427_create_users_auth_table/migration.sql
  prisma/migrations/20220413062222_delete_users_column_o_auth_service_id/migration.sql
  prisma/schema.prisma
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  src/users/auth/dto/get-access-token-using-refresh-token.dto.ts
  src/users/auth/errors/users-auth.error.ts
  src/users/auth/types/users-auth.repository.type.ts
  src/users/auth/users-auth.controller.ts
  src/users/auth/users-auth.decorator.ts
  src/users/auth/users-auth.repository.ts
  src/users/auth/users-auth.service.ts
  src/users/types/users.service.type.ts
  src/users/users.module.ts
  src/users/users.repository.ts
  src/users/users.service.ts
  yarn.lock
Labels: enhancement

#22 유저 액세스 토큰 인증, 버그픽스
  library/open-api/swagger-document-builder.ts
  library/utils/cookie/cookie.service.ts
  library/utils/decorators/jwt-user-Id.decorator.ts
  library/utils/guards/auth/jwt-access-token.guard.ts
  library/utils/guards/auth/strategy/jwt-access-token.strategy.ts
  library/utils/token/types/token.type.ts
  package.json
  src/users/auth/dto/get-access-token-using-refresh-token.dto.ts
  src/users/auth/errors/users-auth.error.ts
  src/users/auth/types/users-auth.repository.type.ts
  src/users/auth/users-auth.controller.ts
  src/users/auth/users-auth.decorator.ts
  src/users/auth/users-auth.repository.ts
  src/users/auth/users-auth.service.ts
  src/users/users.module.ts
  yarn.lock
Labels: bug, documentation

#24 토큰 잘못된 옵션 지정, 쿠키 옵션 누락 해결
  environments/readme.md
  environments/validationSchema.ts
  library/utils/cookie/cookie.service.ts
  src/users/auth/users-auth.repository.ts
Labels: bug

#27 Openapi Typescript-Axios
  .gitignore
  library/swagger/index.ts
  library/swagger/swagger-document-builder.ts
  openapi/package.json
  openapi/readme.md
  openapitools.json
  package.json
  src/main.ts
  yarn.lock
Labels: documentation, enhancement

#32 포스트 생성
  package.json
  prisma/migrations/20220418034331_add_posts_columns/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/posts/dto/create-post.dto.ts
  src/posts/posts.controller.ts
  src/posts/posts.decorator.ts
  src/posts/posts.module.ts
  src/posts/posts.repository.ts
  src/posts/posts.service.ts
Labels: enhancement

#34 게시글 상세조회
  .eslintrc.js
  library/prisma/prisma.service.ts
  library/prisma/type/prisma.type.ts
  prisma/schema.prisma
  src/app.module.ts
  src/posts/dto/create-post.dto.ts
  src/posts/dto/get-post-detail.dto.ts
  src/posts/posts.controller.ts
  src/posts/posts.decorator.ts
  src/posts/posts.module.ts
  src/posts/posts.repository.ts
  src/posts/posts.service.ts
  src/posts/view/posts-view.repository.ts
  src/users/auth/users-auth.repository.ts
  src/users/users.repository.ts
Labels: enhancement

#36 게시글 좋아요 로직
  prisma/migrations/20220419034116_add_postlike_columns/migration.sql
  prisma/schema.prisma
  src/posts/errors/posts.error.ts
  src/posts/like/dto/has-liked.dto.ts
  src/posts/like/dto/set-like.dto.ts
  src/posts/like/dto/unset-like.dto.ts
  src/posts/like/error/posts-like.error.ts
  src/posts/like/posts-like.controller.ts
  src/posts/like/posts-like.decorator.ts
  src/posts/like/posts-like.repository.ts
  src/posts/like/posts-like.service.ts
  src/posts/posts.controller.ts
  src/posts/posts.module.ts
  src/posts/posts.repository.ts
  src/posts/posts.service.ts
  src/users/auth/errors/users-auth.error.ts
Labels: enhancement

#38 게시글 리스트 조회
  library/utils/constants/constants.ts
  library/utils/date/date.ts
  src/posts/dto/get-posts-detail.dto.ts
  src/posts/posts.controller.ts
  src/posts/posts.decorator.ts
  src/posts/posts.repository.ts
  src/posts/posts.service.ts
Labels: enhancement

#40 댓글 생성
  prisma/migrations/20220420110539_add_comments_columns/migration.sql
  prisma/migrations/20220420110759_copy_comments_content/migration.sql
  prisma/migrations/20220420110926_delete_comments_column_html_content/migration.sql
  prisma/migrations/readme.md
  prisma/schema.prisma
  src/app.module.ts
  src/comments/comments.controller.ts
  src/comments/comments.decorator.ts
  src/comments/comments.module.ts
  src/comments/comments.repository.ts
  src/comments/comments.service.ts
  src/comments/dto/create-comment.dto.ts
Labels: enhancement

#41 유저 개인 설정
  prisma/migrations/20220420102426_create_users_setting_table/migration.sql
  prisma/schema.prisma
  src/users/dto/set-setting.dto.ts
  src/users/setting/users-setting.repository.ts
  src/users/setting/users-setting.service.ts
  src/users/users.controller.ts
  src/users/users.decorator.ts
  src/users/users.module.ts
Labels: enhancement

#46 댓글 리스트 조회
  src/comments/comments.controller.ts
  src/comments/comments.decorator.ts
  src/comments/comments.repository.ts
  src/comments/comments.service.ts
  src/comments/dto/get-comments.dto.ts
Labels: enhancement

#48 카테고리 전체 리스트
  prisma/migrations/20220421080622_add_category_column/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/categories/categories.controller.ts
  src/categories/categories.decorator.ts
  src/categories/categories.module.ts
  src/categories/categories.repository.ts
  src/categories/categories.service.ts
  src/categories/dto/get-categories.dto.ts
Labels: enhancement

#51 유저가 사용한 카테고리 리스트
  src/categories/categories.controller.ts
  src/categories/categories.decorator.ts
  src/categories/categories.repository.ts
  src/categories/categories.service.ts
  src/categories/dto/get-user-categories.dto.ts
Labels: enhancement

#53 댓글 삭제
  src/comments/comments.controller.ts
  src/comments/comments.decorator.ts
  src/comments/comments.repository.ts
  src/comments/comments.service.ts
  src/comments/dto/delete-comment.dto.ts
  src/comments/errors/comments.error.ts
Labels: enhancement

#55 댓글 수정
  src/comments/comments.controller.ts
  src/comments/comments.decorator.ts
  src/comments/comments.repository.ts
  src/comments/comments.service.ts
  src/comments/dto/update-comment.dto.ts
  src/comments/errors/comments.error.ts
Labels: enhancement

#56 PR Template 개정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#59 CustomErrorException 개선
  library/all-exceptions/all-exception.filter.ts
  library/all-exceptions/interface/exception-message.interface.ts
  src/app.module.ts
  src/comments/errors/comments.error.ts
  src/posts/errors/posts.error.ts
  src/posts/like/error/posts-like.error.ts
  src/users/auth/errors/users-auth.error.ts
Labels: bug | 💣, enhancement | ⚙️

#63 라이브러리 정리, 경로별칭, 폴더 컨벤션 지정
  library/all-exceptions/index.ts
  library/all-exceptions/type/exception-message.interface.ts
  library/constants/constants.ts
  library/constants/index.ts
  library/cookie/cookie.module.ts
  library/cookie/cookie.service.ts
  library/date/date.ts
  library/date/index.ts
  library/decorators/jwt-user-Id.decorator.ts
  library/guards/auth/github-auth.guard.ts
  library/guards/auth/jwt-access-token.guard.ts
  library/guards/auth/strategy/github.strategy.ts
  library/guards/auth/strategy/jwt-access-token.strategy.ts
  library/token/type/token.type.ts
  library/utils/index.ts
  src/app.module.ts
  src/comments/comments.controller.ts
  src/comments/comments.decorator.ts
  src/comments/comments.repository.ts
  src/comments/comments.service.ts
  src/comments/error/comments.error.ts
  src/posts/dto/get-posts-detail.dto.ts
  src/posts/errors/posts.error.ts
  src/posts/like/error/posts-like.error.ts
  src/posts/like/posts-like.controller.ts
  src/posts/like/posts-like.decorator.ts
  src/posts/like/posts-like.repository.ts
  src/posts/posts.controller.ts
  src/posts/posts.decorator.ts
  src/posts/posts.repository.ts
  src/posts/posts.service.ts
  src/posts/view/posts-view.repository.ts
  src/users/auth/error/users-auth.error.ts
  src/users/auth/users-auth.controller.ts
  src/users/auth/users-auth.decorator.ts
  src/users/auth/users-auth.repository.ts
  src/users/auth/users-auth.service.ts
  src/users/type/users.service.type.ts
  src/users/users.controller.ts
  src/users/users.decorator.ts
  src/users/users.module.ts
  src/users/users.repository.ts
  tsconfig.json
Labels: bug | 💣, enhancement | ⚙️
